# Generated by Django 2.2.4 on 2021-04-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='description',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='author',
            name='name',
        ),
        migrations.AddField(
            model_name='author',
            name='first_name',
            field=models.CharField(default='name', max_length=255),
        ),
        migrations.AddField(
            model_name='author',
            name='last_name',
            field=models.CharField(default='name', max_length=255),
        ),
    ]
