# Generated by Django 2.2.4 on 2021-04-23 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0002_comment_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='date',
        ),
    ]
