# Generated by Django 2.2.4 on 2021-04-21 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserI',
            new_name='User',
        ),
    ]
